### ISSUE TITLE
Route - /login

### ISSUE THREAD

**Issue by dastrong** [chingu-voyages/v19-bears-team-08#3]
Test to make sure all validations work correctly

**Don't send the user's password to the frontend

**Comment by dastrong** [comment]
Oh yea we need to send the JWT to the frontend also.

Could you also send it back with `.json` instead of `.send`?

**Comment by ottotsuma** [comment]
In progress, data still being sent to front.

**Comment by dastrong** [comment]
After some thought and research today, I think this route should only return a token, which can in turn be used to protect routes and get user information.

Thoughts @ottotsuma?

**Comment by ottotsuma** [comment]
Ah i think i was doing similar research I am currently watching up on how to do that, (https://www.youtube.com/watch?v=7nafaH9SddU) so I would say that I agree, seems a bit weird to send back information that the front end has not even requested.

**Comment by dastrong** [comment]
Finished this off today
