### ISSUE TITLE
Route - /register

### ISSUE THREAD

**Issue by dastrong** [chingu-voyages/v19-bears-team-08#4]
Test to make sure all validations work correctly

**Don't send the user's password to the frontend

**Comment by dastrong** [comment]
Oh yea we need to send the JWT to the frontend also.

Could you also send it back with `.json` instead of `.send`?

**Comment by ottotsuma** [comment]
Testing in progress, cannot be marked as complete as the users email and username are sent to the front end currently.

**Comment by ottotsuma** [comment]
Oh do you want /signup instead of /register ?

**Comment by ottotsuma** [comment]
Should we just not send the username / email at all or hash it like the password?

**Comment by dastrong** [comment]
`/register` is fine. *edited title*

Sending the username/email back plainly is acceptable (obviously the password would be a no-no).

Sending the username/email back inside a JWT would be preferable though.

**Comment by ottotsuma** [comment]
Sorry this again, do you want the token sent back as res.json or both the token and the users information sent back as res.json ?

**Comment by dastrong** [comment]
`res.json({token, userObject})`?

**Comment by dastrong** [comment]
Finished this off today
