### ISSUE TITLE
Route - /user

### ISSUE THREAD

**Issue by dastrong** [chingu-voyages/v19-bears-team-08#6]
## Accepts
- an authorization token
> create a reusable middleware function which checks the validity of this token

## Returns
- user object 
> *sans* password

**Comment by ottotsuma** [comment]
I am a little lost with this one, do you mean the verifyToken.js that is in the routes folder, that checks if the token is verified? or is this something else?

**Comment by dastrong** [comment]
`/login` returns a token

`/user` returns the user object

The purpose is two fold. When a user logs in we want to be able to show messages like 'Hello, Daniel'. And the other is if someone clicks on a user's profile.

**Comment by ottotsuma** [comment]
Ah yes it does explain that above, i get it now ^^ sorry

**Comment by ottotsuma** [comment]
Created the /user route but need to add validation

**Comment by dastrong** [comment]
Nice I'll check out the backend tomorrow

**Comment by dastrong** [comment]
I've implemented this, but we might need to expand on it too.

**Comment by dastrong** [comment]
I ended up expanding the user endpoint into two different routes

- `/api/user/profile` take a JWT and send's back the owner of that token
- `/api/user` accepts three different query params and returns the non sensitive user data from that
